# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildLinux
  displayName: Build for Linux
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    CC: gcc-7
    CXX: g++-7
  steps:
  - bash: |
      set -euo pipefail

      cd $(Agent.TempDirectory)
      wget -q "https://github.com/Kitware/CMake/releases/download/v3.15.0/cmake-3.15.0-Linux-x86_64.tar.gz"
      tar zxf cmake-3.15.0-Linux-x86_64.tar.gz
      mv cmake-3.15.0-Linux-x86_64 cmake
      cd $(Build.SourcesDirectory)
      mkdir build
    displayName: Install CMake 3.15
  - bash: |
      $(Agent.TempDirectory)/cmake/bin/cmake --version
      $(Agent.TempDirectory)/cmake/bin/cmake -S .. -B .
    workingDirectory: build
    displayName: Build project files
  - bash: |
      $(Agent.TempDirectory)/cmake/bin/cmake --build . --config Release
    workingDirectory: build
    displayName: Compile project
